// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: UI v5

#include "../ui.h"

void ui_Setup_Screen_screen_init(void)
{
    ui_Setup_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Setup_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Setup_Screen, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setup_Screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ta_aux_1 = lv_textarea_create(ui_Setup_Screen);
    lv_obj_set_width(ui_ta_aux_1, 160);
    lv_obj_set_height(ui_ta_aux_1, 45);
    lv_obj_set_x(ui_ta_aux_1, -300);
    lv_obj_set_y(ui_ta_aux_1, -215);
    lv_obj_set_align(ui_ta_aux_1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_ta_aux_1, "AUX 1");
    lv_obj_set_style_text_align(ui_ta_aux_1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ta_aux_1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ta_aux_1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_ta_aux_2 = lv_textarea_create(ui_Setup_Screen);
    lv_obj_set_width(ui_ta_aux_2, 160);
    lv_obj_set_height(ui_ta_aux_2, 45);
    lv_obj_set_x(ui_ta_aux_2, -100);
    lv_obj_set_y(ui_ta_aux_2, -215);
    lv_obj_set_align(ui_ta_aux_2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_ta_aux_2, "AUX 2");
    lv_obj_set_style_text_align(ui_ta_aux_2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ta_aux_2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ta_aux_2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_ta_aux_3 = lv_textarea_create(ui_Setup_Screen);
    lv_obj_set_width(ui_ta_aux_3, 160);
    lv_obj_set_height(ui_ta_aux_3, 45);
    lv_obj_set_x(ui_ta_aux_3, 100);
    lv_obj_set_y(ui_ta_aux_3, -215);
    lv_obj_set_align(ui_ta_aux_3, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_ta_aux_3, "AUX 3");
    lv_obj_set_style_text_letter_space(ui_ta_aux_3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_ta_aux_3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ta_aux_3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ta_aux_3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ta_aux_3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_ta_aux_4 = lv_textarea_create(ui_Setup_Screen);
    lv_obj_set_width(ui_ta_aux_4, 160);
    lv_obj_set_height(ui_ta_aux_4, 45);
    lv_obj_set_x(ui_ta_aux_4, 300);
    lv_obj_set_y(ui_ta_aux_4, -215);
    lv_obj_set_align(ui_ta_aux_4, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_ta_aux_4, "AUX 4");
    lv_obj_set_style_text_align(ui_ta_aux_4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ta_aux_4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ta_aux_4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_ta_aux_5 = lv_textarea_create(ui_Setup_Screen);
    lv_obj_set_width(ui_ta_aux_5, 160);
    lv_obj_set_height(ui_ta_aux_5, 45);
    lv_obj_set_x(ui_ta_aux_5, -300);
    lv_obj_set_y(ui_ta_aux_5, -160);
    lv_obj_set_align(ui_ta_aux_5, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_ta_aux_5, "AUX 5");
    lv_obj_set_style_text_align(ui_ta_aux_5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ta_aux_5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ta_aux_5, 20, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_ta_aux_6 = lv_textarea_create(ui_Setup_Screen);
    lv_obj_set_width(ui_ta_aux_6, 160);
    lv_obj_set_height(ui_ta_aux_6, 45);
    lv_obj_set_x(ui_ta_aux_6, -100);
    lv_obj_set_y(ui_ta_aux_6, -160);
    lv_obj_set_align(ui_ta_aux_6, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_ta_aux_6, "AUX 6");
    lv_obj_set_style_text_align(ui_ta_aux_6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ta_aux_6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ta_aux_6, 20, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_ta_aux_7 = lv_textarea_create(ui_Setup_Screen);
    lv_obj_set_width(ui_ta_aux_7, 160);
    lv_obj_set_height(ui_ta_aux_7, 45);
    lv_obj_set_x(ui_ta_aux_7, 100);
    lv_obj_set_y(ui_ta_aux_7, -160);
    lv_obj_set_align(ui_ta_aux_7, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_ta_aux_7, "AUX 7");
    lv_obj_set_style_text_align(ui_ta_aux_7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ta_aux_7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ta_aux_7, 20, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_ta_aux_8 = lv_textarea_create(ui_Setup_Screen);
    lv_obj_set_width(ui_ta_aux_8, 160);
    lv_obj_set_height(ui_ta_aux_8, 45);
    lv_obj_set_x(ui_ta_aux_8, 300);
    lv_obj_set_y(ui_ta_aux_8, -160);
    lv_obj_set_align(ui_ta_aux_8, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_ta_aux_8, "AUX 8");
    lv_obj_set_style_text_align(ui_ta_aux_8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ta_aux_8, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_ta_aux_8, 20, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Keyboard2 = lv_keyboard_create(ui_Setup_Screen);
    lv_keyboard_set_mode(ui_Keyboard2, LV_KEYBOARD_MODE_TEXT_UPPER);
    lv_obj_set_width(ui_Keyboard2, 800);
    lv_obj_set_height(ui_Keyboard2, 260);
    lv_obj_set_x(ui_Keyboard2, 0);
    lv_obj_set_y(ui_Keyboard2, 100);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_radius(ui_Keyboard2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Keyboard2, lv_color_hex(0x443333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Keyboard2, 100, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Keyboard2, lv_color_hex(0x78A983), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard2, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Keyboard2, lv_color_hex(0xFFFFFF), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Keyboard2, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Keyboard2, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Keyboard2, 4, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Keyboard2, LV_BORDER_SIDE_FULL, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Keyboard2, lv_color_hex(0x000000), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Keyboard2, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Keyboard2, &lv_font_montserrat_22, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_Save_Button = lv_btn_create(ui_Setup_Screen);
    lv_obj_set_width(ui_Save_Button, 120);
    lv_obj_set_height(ui_Save_Button, 80);
    lv_obj_set_x(ui_Save_Button, 306);
    lv_obj_set_y(ui_Save_Button, -80);
    lv_obj_set_align(ui_Save_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Save_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Save_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Save_Button, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Save_Button, lv_color_hex(0x616161), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Save_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Save_Button, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Save_Button, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_Save_Button, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Save_Button, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Save_Label = lv_label_create(ui_Save_Button);
    lv_obj_set_width(ui_Save_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Save_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Save_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Save_Label, "SAVE");
    lv_obj_add_flag(ui_Save_Label, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_Save_Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Save_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Save_Label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ta_aux_1, ui_event_ta_aux_1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ta_aux_2, ui_event_ta_aux_2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ta_aux_3, ui_event_ta_aux_3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ta_aux_4, ui_event_ta_aux_4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ta_aux_5, ui_event_ta_aux_5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ta_aux_6, ui_event_ta_aux_6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ta_aux_7, ui_event_ta_aux_7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ta_aux_8, ui_event_ta_aux_8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Save_Label, ui_event_Save_Label, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Save_Button, ui_event_Save_Button, LV_EVENT_ALL, NULL);
    uic_ta_aux_1 = ui_ta_aux_1;
    uic_ta_aux_2 = ui_ta_aux_2;
    uic_ta_aux_3 = ui_ta_aux_3;
    uic_ta_aux_4 = ui_ta_aux_4;
    uic_ta_aux_5 = ui_ta_aux_5;
    uic_ta_aux_6 = ui_ta_aux_6;
    uic_ta_aux_7 = ui_ta_aux_7;
    uic_ta_aux_8 = ui_ta_aux_8;
    uic_Save_Button = ui_Save_Button;
    uic_Save_Label = ui_Save_Label;

}
