// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: UI v5

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void aux_1_on(lv_event_t * e);
void aux_1_off(lv_event_t * e);
void aux_2_on(lv_event_t * e);
void aux_2_off(lv_event_t * e);
void aux_3_on(lv_event_t * e);
void aux_3_off(lv_event_t * e);
void aux_4_on(lv_event_t * e);
void aux_4_off(lv_event_t * e);
void aux_5_on(lv_event_t * e);
void aux_5_off(lv_event_t * e);
void aux_6_on(lv_event_t * e);
void aux_6_off(lv_event_t * e);
void aux_7_on(lv_event_t * e);
void aux_7_off(lv_event_t * e);
void aux_8_on(lv_event_t * e);
void aux_8_off(lv_event_t * e);
void update_voltage_event_handler(lv_event_t * e);
void update_voltage_label(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
